title: Mijn script wordt niet geactiveerd als ik bots met een ander GameObject
hero_image: images/banner.png
description: Mijn script wordt niet geactiveerd als ik bots met een ander GameObject
version: 4
listed: false
copyedit: false
last_tested: "2021-11-23"
steps:
  - 
    title: Mijn script wordt niet geactiveerd als ik bots met een ander GameObject
