---
title: Mon script ne se déclenche pas lorsque j'entre en collision avec un autre GameObject
hero_image: images/banner.png
description: Mon script ne se déclenche pas lorsque j'entre en collision avec un autre GameObject
version: 4
listed: false
copyedit: false
last_tested: "2021-11-23"
steps:
  - title: Mon script ne se déclenche pas lorsque j'entre en collision avec un autre GameObject
